package piratascaribe;

import java.util.HashMap;
import java.util.Map;

public class maquina3 extends javax.swing.JFrame {
    private static final long serialVersionUID = 1L;
      private Map<String,Coordenada> coordenadas = new HashMap<String,Coordenada>();
    /**
     * Creates new form maquina2
     */
    public maquina3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
                            
    private void initComponents() {

        this.setTitle("Maquina 3");
        CuevadelosHuesos = new javax.swing.JLabel();
        BahiadelBuenRetiro = new javax.swing.JLabel();
        BahiadelasFlores = new javax.swing.JLabel();
        CementeriodeBarcos = new javax.swing.JLabel();
        CayodeBarlovento = new javax.swing.JLabel();
        IslaTortuga = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        

        BahiadelBuenRetiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/m3-retiro.png"))); // NOI18N
        getContentPane().add(BahiadelBuenRetiro);
        BahiadelBuenRetiro.setBounds(610, 400, 100, 80);
        coordenadas.put("Bahia del Buen Retiro", new Coordenada(610,400));

        BahiadelasFlores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/m3-flores.png"))); // NOI18N
        getContentPane().add(BahiadelasFlores);
        BahiadelasFlores.setBounds(220, 80, 90, 90);
        coordenadas.put("Bahia de las Flores",new Coordenada(220 , 80));

        CementeriodeBarcos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/m3-cemeterio.png"))); // NOI18N
        getContentPane().add(CementeriodeBarcos);
        CementeriodeBarcos.setBounds(140, 210, 100, 70);
        coordenadas.put("Cementerio de Barcos", new Coordenada(140,210));

        CayodeBarlovento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Barlovento.png"))); // NOI18N
        getContentPane().add(CayodeBarlovento);
        CayodeBarlovento.setBounds(490, 60, 260, 180);
        coordenadas.put("Cayo de Barlovento", new Coordenada(490,60));
        
        CuevadelosHuesos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/m3-cuevahuesos.png"))); // NOI18N
        getContentPane().add(CuevadelosHuesos);
        CuevadelosHuesos.setBounds(410, 430, 110, 80);
        coordenadas.put("Cueva de los Huesos",new Coordenada(410,430));

        IslaTortuga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/maquina3.png"))); // NOI18N
        getContentPane().add(IslaTortuga);
        IslaTortuga.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>                        

    public Map<String,Coordenada> getCoordenadas (){
        return coordenadas;
    }


    // Variables declaration - do not modify                     
    private javax.swing.JLabel IslaTortuga;
    private javax.swing.JLabel CuevadelosHuesos;
    private javax.swing.JLabel BahiadelBuenRetiro;
    private javax.swing.JLabel BahiadelasFlores;
    private javax.swing.JLabel CementeriodeBarcos;
    private javax.swing.JLabel CayodeBarlovento;
    // End of variables declaration                   
}
