package piratascaribe;

import java.util.HashMap;
import java.util.Map;

public class maquina4 extends javax.swing.JFrame {
    private static final long serialVersionUID = 1L;
      private Map<String,Coordenada> coordenadas = new HashMap<String,Coordenada>();
    

    /**
     * Creates new form maquina2
     */
    public maquina4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
                            
    private void initComponents() {
        this.setTitle("Maquina 4");

        CuevadelPirata = new javax.swing.JLabel();
        CayodelosPelicanos = new javax.swing.JLabel();
        BahiadelTesoroPerdido = new javax.swing.JLabel();
        PuertoRico = new javax.swing.JLabel();
        PuertodelasBallenas = new javax.swing.JLabel();
        LaGranIsladelaEspañola = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        

        CayodelosPelicanos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cayopelicano.png"))); // NOI18N
        getContentPane().add(CayodelosPelicanos);
        CayodelosPelicanos.setBounds(350, 310, 470, 270);
        coordenadas.put("Cayo de los Pelicanos",new Coordenada (350, 310));

        BahiadelTesoroPerdido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/m4-tesoroperdido.png"))); // NOI18N
        getContentPane().add(BahiadelTesoroPerdido);
        BahiadelTesoroPerdido.setBounds(420, 210, 100, 80);
        coordenadas.put("Bahia del Tesoro Perdido",new Coordenada (420, 210));
        
        
        PuertoRico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/m4-puertorico.png"))); // NOI18N
        getContentPane().add(PuertoRico);
        PuertoRico.setBounds(460, 70, 93, 70);
        coordenadas.put("Puerto Rico",new Coordenada(460,70));

        PuertodelasBallenas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/m4-puertoballena.png"))); // NOI18N
        getContentPane().add(PuertodelasBallenas);
        PuertodelasBallenas.setBounds(90, 50, 90, 60);
        coordenadas.put("Puerto de las Ballenas", new Coordenada(90,50));
        
        CuevadelPirata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/m4-cuevapiratag.png"))); // NOI18N
        getContentPane().add(CuevadelPirata);
        CuevadelPirata.setBounds(170, 210, 100, 90);
        coordenadas.put("Cueva del Pirata", new Coordenada(170,210));

        LaGranIsladelaEspañola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/maquina4.png"))); // NOI18N
        getContentPane().add(LaGranIsladelaEspañola);
        LaGranIsladelaEspañola.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>                        

 
    public Map<String,Coordenada> getCoordenadas (){
        return coordenadas;
    }
    // Variables declaration - do not modify                     
    private javax.swing.JLabel LaGranIsladelaEspañola;
    private javax.swing.JLabel CuevadelPirata;
    private javax.swing.JLabel CayodelosPelicanos;
    private javax.swing.JLabel BahiadelTesoroPerdido;
    private javax.swing.JLabel PuertoRico;
    private javax.swing.JLabel PuertodelasBallenas;
    // End of variables declaration                   
}
